/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "interface_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace brkservice {

} // namespace
