/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef interface_CONSTANTS_H
#define interface_CONSTANTS_H

#include "interface_types.h"

namespace brkservice {

class interfaceConstants {
 public:
  interfaceConstants();

};

extern const interfaceConstants g_interface_constants;

} // namespace

#endif
