/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef struct_CONSTANTS_H
#define struct_CONSTANTS_H

#include "struct_types.h"

namespace brkservice {

class structConstants {
 public:
  structConstants();

};

extern const structConstants g_struct_constants;

} // namespace

#endif
