/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "struct_constants.h"

namespace brkservice {

const structConstants g_struct_constants;

structConstants::structConstants() {
}

} // namespace

